api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld:
            mime_types:
                - application/jsonld
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
    #patch_formats:
    #    json: ['application/merge-patch+json']
    swagger:
        versions: [3]