pre_composer_script: |
    #!/bin/bash
    cp app/config/parameters.yml.dist app/config/parameters.yml
    sed -i -e "s/secret:.*/secret: 4c35b7b283e0df29cf6034d9ddd631c8a4b8f5f1/" app/config/parameters.yml
    sed -i -e "s/database_name:.*/database_name: obblm/" app/config/parameters.yml

post_composer_script: |
    #!/bin/bash
    ./app/console doctrine:database:create --no-interaction
    ./app/console doctrine:schema:update --force --no-interaction
    ./app/console assets:install web --symlink --no-interaction
    #./app/console doctrine:fixtures:load --no-interaction
