sudo: false

language: php

php:
  - 7.1
  - 7.2

node_js:
  - "4.1"
  - "4.0"

before_install:
  - composer self-update
  - npm install

install:
  - composer install
  - grunt

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load --env=test -n
  - php bin/console cache:clear --env=test

script: vendor/bin/phpunit
