sudo: false

language: php

php:
  - 5.5
  - 5.6

node_js:
  - "4.1"
  - "4.0"

before_install:
  - composer self-update
  - npm install

install:
  - composer install
  - grunt

script: phpunit -c app
