fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: BbLeagueBundle\Entity\Coach
    from_email:
        address:        "%fos_user_from_email%"
        sender_name:    "%fos_user_from_name%"
