app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

bblm_manager:
    resource: "@BbLeagueBundle/Resources/config/routing.yml"
