bb_ligue:
    rules:
        lrb6:
            max_team_cost: 1000000
            skills:
                g:
                    - block
                    - dauntless
                    - dirty_player
                    - fend
                    - frenzy
                    - kick
                    - kick_off_return
                    - pass_block
                    - pro
                    - shadowing
                    - strip_ball
                    - sure_hands
                    - tackle
                    - wrestle
                a:
                    - catch
                    - diving_catch
                    - diving_tackle
                    - dodge
                    - jump_up
                    - leap
                    - side_step
                    - sneaky_git
                    - sprint
                    - sure_feet
                p:
                    - accurate
                    - dump_off
                    - hail_mary_pass
                    - leader
                    - nerves_of_steel
                    - pass
                    - safe_throw
                s:
                    - break_tackle
                    - grab
                    - guard
                    - juggernaut
                    - mighty_blow
                    - multiple_block
                    - piling_on
                    - stand_firm
                    - strong_arm
                    - thick_skull
                m:
                    - big_hand
                    - claw_claws
                    - disturbing_presence
                    - extra_arms
                    - foul_appearance
                    - horns
                    - prehensile_tail
                    - tentacles
                    - two_heads
                    - very_long_legs
                e:
                    - always_hungry
                    - animosity
                    - ball_chain
                    - blood_lust
                    - bombardier
                    - bone_head
                    - chainsaw
                    - decay
                    - fan_favourite
                    - hypnotic_gaze
                    - loner
                    - no_hands
                    - nurgle_rot
                    - really_stupid
                    - regeneration
                    - right_stuff
                    - secret_weapon
                    - stab
                    - stakes
                    - stunty
                    - take_root
                    - throw_team_mate
                    - titchy
                    - wild_animal
