bb_ligue:
    rules:
        lrb6:
            rosters:
                dwarf:
                    players:
                        slayer:
                            min: 0
                            max: 2
                            move: 5
                            force: 3
                            agility: 2
                            armor: 8
                            cost: 90000
                            skills: ['block', 'thick_skull', 'dauntless']
                            available_skills: ['g', 's']
                            available_skills_on_double: ['a', 'p']
                        blitzer:
                            min: 0
                            max: 2
                            move: 5
                            force: 3
                            agility: 3
                            armor: 9
                            cost: 80000
                            skills: ['block', 'thick_skull']
                            available_skills: ['g', 's']
                            available_skills_on_double: ['a', 'p']
                        runner:
                            min: 0
                            max: 2
                            move: 6
                            force: 3
                            agility: 3
                            armor: 8
                            cost: 80000
                            skills: ['sure_hands', 'thick_skull']
                            available_skills: ['g', 'p']
                            available_skills_on_double: ['s', 'a']
                        blocker:
                            min: 0
                            max: 16
                            move: 4
                            force: 3
                            agility: 2
                            armor: 9
                            cost: 70000
                            skills: ['block', 'thick_skull', 'tackle']
                            available_skills: ['g', 's']
                            available_skills_on_double: ['a', 'p']
                        death_roller:
                            min: 0
                            max: 1
                            move: 4
                            force: 7
                            agility: 1
                            armor: 10
                            cost: 160000
                            skills: ['loner', 'secret_weapon', 'break_tackle', 'mighty_blow', 'dirty_player', 'juggernaut', 'no_hands', 'stand_firm']
                            available_skills: ['s']
                            available_skills_on_double: ['g', 'a', 'p']
                    options:
                        reroll_cost: 50000
                        available_star_players: []
                        can_have_alchemist: true
                        can_have_sorcerer: true
                        can_have_igor: false
                        can_have_halfing_kitchener: false
