bb_ligue:
    rules:
        lrb6:
            rosters:
                goblin:
                    players:
                        goblin:
                            min: 0
                            max: 16
                            ma: 6
                            st: 2
                            ag: 3
                            av: 7
                            skills: [ 'dodge', 'right_stuff', 'stunty' ]
                            cost: 40000
                            available_skills: ['a']
                            available_skills_on_double: ['g', 's', 'p']
                        bombardier:
                            min: 0
                            max: 1
                            ma: 6
                            st: 2
                            ag: 3
                            av: 7
                            skills: [ 'bombardier', 'dodge', 'secret_weapon', 'stunty' ]
                            cost: 40000
                            available_skills: ['a']
                            available_skills_on_double: ['g', 's', 'p']
                        looney:
                            min: 0
                            max: 1
                            ma: 6
                            st: 2
                            ag: 3
                            av: 7
                            skills: [ 'chainsaw', 'secret_weapon', 'stunty' ]
                            cost: 40000
                            available_skills: ['a']
                            available_skills_on_double: ['g', 's', 'p']
                        fanatic:
                            min: 0
                            max: 1
                            ma: 3
                            st: 7
                            ag: 3
                            av: 7
                            skills: [ 'ball_chain', 'no_hands', 'secret_weapon,', 'stunty' ]
                            cost: 70000
                            available_skills: ['s']
                            available_skills_on_double: ['g', 'a', 'p']
                        pogoer:
                            min: 0
                            max: 1
                            ma: 7
                            st: 2
                            ag: 3
                            av: 7
                            skills: [ 'dodge', 'leap', 'stunty', 'very_long_legs' ]
                            cost: 70000
                            available_skills: ['a']
                            available_skills_on_double: ['g', 's', 'p']
                        troll:
                            min: 0
                            max: 2
                            ma: 4
                            st: 5
                            ag: 1
                            av: 9
                            skills: [ 'loner', 'always_hungry', 'mighty_blow', 'really_stupid', 'regeneration', 'throw_team_mate' ]
                            cost: 110000
                            available_skills: ['s']
                            available_skills_on_double: ['g', 'a', 'p']
                    options:
                        reroll_cost: 60000
                        available_star_players: [bomber_dribblesnot, fungus_the_Loon, morg_n_thorg, nobbla_blackwart, scrappa_sorehead, ripper]
                        can_have_apothecary: true
                        can_have_sorcerer: true
                        can_have_igor: false
                        can_have_halfing_kitchener: false
