bb_league:
    rules:
        lrb6:
            rosters:
                high_elf:
                    players:
                        zombi:
                            min: 0
                            max: 16
                            ma: 4
                            st: 3
                            ag: 2
                            av: 8
                            skills: [ 'regeneration' ]
                            cost: 40000
                            available_skills: ['g']
                            available_skills_on_double: ['a', 's', 'p']
                        ghoul:
                            min: 0
                            max: 2
                            ma: 7
                            st: 3
                            ag: 3
                            av: 7
                            skills: [ 'dodge' ]
                            cost: 70000
                            available_skills: ['g', 'a']
                            available_skills_on_double: ['s', 'p']
                        wight:
                            min: 0
                            max: 2
                            ma: 6
                            st: 3
                            ag: 3
                            av: 8
                            skills: [ 'block', 'regeneration' ]
                            cost: 90000
                            available_skills: ['g', 's']
                            available_skills_on_double: ['a', 'p']
                        golem:
                            min: 0
                            max: 2
                            ma: 7
                            st: 3
                            ag: 4
                            av: 8
                            skills: [ 'regeneration', 'stand_firm', 'thick_skull' ]
                            cost: 110000
                            available_skills: ['g', 's']
                            available_skills_on_double: ['a', 'p']
                        werewolf:
                            min: 0
                            max: 2
                            ma: 7
                            st: 3
                            ag: 4
                            av: 8
                            skills: [ 'claw_claws', 'frenzy', 'regeneration' ]
                            cost: 120000
                            available_skills: ['g', 'a']
                            available_skills_on_double: ['s', 'p']
                    options:
                        reroll_cost: 70000
                        available_star_players: [hack_enslash, j_earlice, setekh, wilhelm_chaney, ramtut, count_luthor_von_drakenborg]
                        can_have_apothecary: false
                        can_have_sorcerer: true
                        can_have_igor: true
                        can_have_halfing_kitchener: false
